"                       "
"   Yayg's vim config   "
"    No comments ...    "
"                       "

let g:hybrid_use_Xresources = 1
colorscheme hybrid

set nocompatible
filetype off                  " required


"                   "
"  GLOBAL SETTINGS  "
"                   "


"+--- Graphics ---+"
syntax on " Enable syntax highlighting
set number
set relativenumber " Enable relative line number


"+--- Coding Style ---+"
set list
set listchars=trail:•,extends:#,nbsp:. "Highlight problematic indent
set colorcolumn=+1                  " Set a colored column to textwidth + 1
set textwidth=79                    " 'Max' text width
filetype indent on
set autoindent                      " Indent when filetype fail
set softtabstop=4                   " Number of spaces when you press tab
set smarttab
set shiftwidth=4                    " Indent level
set expandtab                       " Replace classical tabs by spaces


"+--- Misc ---+"
" Reload a file when it is changed from the outside
set autoread
set hlsearch                        " Highlight search term
set wildmenu                        " Command line completion
set wildmode=list:longest:full      " Command line completion kind



"                   "
"    VUNDLE AREA    "
"                   "

"+--- Set up vundle ---+"
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle
call vundle#begin()
"call vundle#begin('~/some/path/')

" let Vundle manage Vundle, required
Plugin 'gmarik/vundle'


"+--- Syntastic ---+"
Plugin 'scrooloose/syntastic'
let g:syntastic_c_compiler='gcc' " Use clang instead of gcc
let g:syntastic_c_compiler_options = '-Wall -Wextra -pedantic -std=c99'
let g:syntastic_c_check_header=1 " Check headers in c
let g:syntastic_cpp_compiler = 'clang++' " Use clang++ instead of g++
let g:syntastic_cpp_compiler_options = '-Wall -Wextra -pedantic -std=c++11'
let g:syntastic_cpp_check_header=1 " Check headers in c++
let g:syntastic_ocaml_use_ocamlc =0 "dd Use ocamlc instead of ocamlopt


"+--- Completion ---+"
Plugin 'Valloric/YouCompleteMe'


"+--- Colorscheme ---+"
Plugin 'spf13/vim-colors'
Plugin 'bling/vim-airline'
set laststatus=2
let g:Powerline_symbols = "fancy"
let g:airline_powerline_fonts =0
" unicode symbols
  let g:airline_left_sep = '»'
  let g:airline_left_sep = '▶'
  let g:airline_right_sep = '«'
  let g:airline_right_sep = '◀'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
